steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/homestager-backend:$COMMIT_SHA'
      - './backend'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/homestager-backend:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'homestager-backend'
      - '--image=gcr.io/$PROJECT_ID/homestager-backend:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
